### PR TITLE
Add a filter for Facebook URL regex validation

### PR DESCRIPTION
**Pull request by astratagem**
Few of the other shortcode classes use this sort of regex URL validation
in the callback methods. These patterns may change unpredictably at any time.

### CODE REVIEW

**Comment by goldenapples** [comment]
I think there was a reason why we had this explicit post URL structure validation in place, so that we could give our editors a heads-up when trying to embed a structure that wasn't supported yet. 

But this works in our newsroom because we have (or had) a quick feedback loop, where we'll hear in a few minutes that an editor is trying to post something that doesn't work through the existing post element, we can test it out and see if it'd work, and either update the validation rules or find an alternative way of embedding that post. When there's a post format that doesn't work with embedding, as happened recently with the 360 video posts that Facebook introduced, it was useful to have an error message on our end that we don't support that kind of embed rather than let the post element be inserted and then have it fail on the front end.

But this plugin is less-actively updated now than it was when we introduced this validation, and without being able to be quickly responsive to new formats, it's not that helpful of a check. 

I'm wondering if it makes more sense to add a filter there, so that sites can override the validation if they find new acceptable patterns that aren't included in the plugin's validation rules, or just to remove the validation rules altogether. Anyone else have opinions one way or the other on this?

**Comment by montchr** [comment]
> I'm wondering if it makes more sense to add a filter there, so that sites can override the validation if they find new acceptable patterns that aren't included in the plugin's validation rules, or just to remove the validation rules altogether.

That solution sounds like a good compromise. I can update my PR if you like, or open a new one.

**Comment by davisshaver** [comment]
Filter/patch loop seems fine. @montchr if you have any examples of bad structures we can get those added.

**Comment by montchr** [comment]
@goldenapples I've reverted my first commit and instead added a filter.

> if you have any examples of bad structures we can get those added.

@davisshaver I don't recall which pattern was giving us trouble, so let's just say it's all good. My approach to using this with a filter:

```php
add_filter( 'shortcake_bakery_facebook_url_patterns', function( $patterns ) {
    return array_merge( $patterns, [
        '#https?:\/\/www?\.facebook\.com\/?#',
    ] );
} );
```

So if some Facebook URL doesn't work with that — a public event, for example — I get the following when rendered:

**Review by goldenapples — APPROVED** [review]
Looks good to me, and it seems like this makes it easy enough to allow all url patterns as you're doing in your example, or to whitelist only the ones that are known to work.

It'd be nice to have phpdoc comments for all the filters in the plugin. Would it make sense to extract this list of whitelisted regexes - and the filter - into a separate method the way that it's done on the [script](https://github.com/wp-shortcake/shortcake-bakery/blob/master/inc/shortcodes/class-script.php#L23-L32) and [iframe](https://github.com/wp-shortcake/shortcake-bakery/blob/master/inc/shortcodes/class-iframe.php#L41-L50) shortcodes?

**Comment by montchr** [comment]
> It'd be nice to have phpdoc comments for all the filters in the plugin. Would it make sense to extract this list of whitelisted regexes - and the filter - into a separate method the way that it's done on the script and iframe shortcodes?

Good call, I can do that.

**Comment by montchr** [comment]
@goldenapples updated

**Pull request merged**
