### PR TITLE
Prepare v0.2.0 for release

### PR DESCRIPTION
**Pull request by goldenapples**
Adds changelog, new plugin headers, and updated language files for v0.2.0
release.  Updates the list of shortcodes available, and adds some documentation
about the "Add Embed" button, and some of the new filters available.

### CODE REVIEW

**Comment by goldenapples** [comment]
@davisshaver While pushing out a new Shortcake release earlier today, I noticed that we hadn't bundled a release of this plugin for well over a year. (I could have sworn that this had been released before, but `¯\_(ツ)_/¯`  I guess it never did?)

It'd be nice to push this out since there's a lot of new stuff - especially as compared to the version that's actually in the plugin repo, which is minimally useful at best. Want to give these release notes a review behind me before we tag and release it?

**Comment by goldenapples** [comment]
Or, if you'd like to finish up the Apple Live Photo shortcode in #208, we could just as well ghet that in and close a few more of the open issues before tagging a release.

**Comment by davisshaver** [comment]
@goldenapples Looks great! Made a few minor tweaks and added the `[live-photo]` shortcode assuming we will merge https://github.com/wp-shortcake/shortcake-bakery/pull/208.

**Comment by davisshaver** [comment]
@goldenapples Did you want any help merging https://github.com/wp-shortcake/shortcake-bakery/pull/203 for v0.2.0?

**Comment by goldenapples** [comment]
I'd like to add some screenshots from the "Add Embed" PR, and a bit of documentation about the CORS proxy, before finishing this off. I'll have a couple more commits incoming...

**Comment by goldenapples** [comment]
OK, I've updated. We'll just have to rebuild the language files (`grunt makepot`) one more time after merging #203, since that adds a new translatable string.

**Pull request merged**
