### PR TITLE
Set better default proportions for Giphy embed; allow override h/w

### LINKED ISSUE #149: giphy shortcode crops gif
Here's the GIF on my site:

Note that bottom text is cut off.

Here's the full-sized GIF on Giphy:

Seems that in making the small-sized GIF full-width, it crops the image.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #149

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@goldenapples #reviewmerge

**Comment by danielbachhuber** [comment]
@montchr This fixes your issue for me. I suppose if we can't know the actual width / height of the Giphy, then we'll need to allow manual override.

**Comment by goldenapples** [comment]
This looks good. I think it makes sense to add support for height/width in the reversal process too, though?

The giphy embed code includes a height and width: `<iframe src="//giphy.com/embed/YqGeOQ0u6hB5u" width="480" height="501" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/YqGeOQ0u6hB5u">via GIPHY</a></p>`

Extracting those and setting them on the shortcode would ensure that we keep the right proportions on display.

**Comment by danielbachhuber** [comment]
> I think it makes sense to add support for height/width in the reversal process too, though?

Good call. Updated.

**Comment by goldenapples** [comment]
Looks good! I noted one unrelated bug as #151. But I'll merge this.

**Pull request merged**
