### PR TITLE
Add Apple Live Photo shortcode

### PR DESCRIPTION
**Pull request by davisshaver**
see https://developer.apple.com/reference/livephotoskitjs

### CODE REVIEW

**Comment by davisshaver** [comment]
Markup on Apple site:

```
<span
  data-live-photo
  data-photo-src="/live-photos/assets/boy.jpg"
  data-video-src="/live-photos/assets/boy.mov"
  data-proactively-loads-video="true"
></span>
```

Markup on my site:

```
<div
  data-live-photo
  data-proactively-loads-video=true
  data-photo-src="https://davisshaver.com/wp-content/uploads/sites/4/2017/04/boy.jpg"
  data-video-src="https://davisshaver.com/wp-content/uploads/sites/4/2017/04/boy.mov">
</div>
```

https://davisshaver.com/2017/04/21/test-live-photo/

**Comment by davisshaver** [comment]
Working example here https://davisshaver.com/2017/04/27/testing-live-photos-on-wordpress-again/

**Comment by goldenapples** [comment]
Looks great! I'll merge, unless there's anything else you're hoping to do with this.

I think it might be good to add a more recognizable icon, but I'm not sure what exactly that would be. I found this one that might work:

apple-live-photo

**Comment by davisshaver** [comment]
@goldenapples I dig the icon! I can drop in tomorrow

**Comment by davisshaver** [comment]
@goldenapples new icon swapped in ✔️

**Comment by goldenapples** [comment]
Looks great! I'll merge this now...

**Pull request merged**
