### PR TITLE
Properly parse YouTube shortcodes on preview

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #145

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@goldenapples #reviewmerge

**Comment by goldenapples** [comment]
Only comment I have is that this kind of unescaping seems like pretty common functionality that maybe should be handled in `parse_url()`. But that can be done in a later refactor when we start to see where it's necessary.

**Comment by danielbachhuber** [comment]
> But that can be done in a later refactor when we start to see where it's necessary.

Yeah. I thought about doing adding the logic deeper, but didn't want to run into any unexpected edge cases. Seemed better to make a localized fix for now.

**Comment by montchr** [comment]
:clap:

**Pull request merged**
